# Generated by Django 2.2.6 on 2019-10-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20191016_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pk',)},
        ),
    ]
